### ISSUE TITLE
Tabs are now broken

### ISSUE THREAD

**Issue by kory-u** [Seraaron/roll20-character-sheets#3]
Changing tabs suddenly stopped working in the middle of a session

**Comment by rotoclone** [comment]
My group is also seeing this, I created an issue on the main repo for it before I found the link to this fork in the readme: https://github.com/Roll20/roll20-character-sheets/issues/7819

**Comment by jaredskarma** [comment]
The updated sheet looks great and I'm loving the new Rogues tab, but my group is also currently experiencing the broken tabs issue.

**Comment by Anduh** [comment]
Roll20 Character Sheet Backend Changes where rolled out yesterday, are likely the cause of this issue. Seem [my comment](https://app.roll20.net/forum/permalink/9556767/) in the main thread for an full explanation.

The issue is identified, and a fix will be out later today, is what I was just told.

**Comment by rotoclone** [comment]
It's working for me as of today

**Comment by Seraaron** [comment]
Yeah this was a server-wide issue with many sheets, not the the Burning Wheel one. Not my fault, luckily! But I think it's already been fixed by the R20 team
